### ISSUE TITLE
HaTeX-3.18.0.0 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [Daniel-Diaz/HaTeX#113]
~~~
Text/LaTeX/Base/Warnings.hs:50:10: error:
    • No instance for (Semigroup TeXCheck)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid TeXCheck’
   |
50 | instance Monoid TeXCheck where
   |          ^^^^^^^^^^^^^^^
~~~

See https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid for details.

**Comment by leftaroundabout** [comment]
This [has already been fixed](https://github.com/Daniel-Diaz/HaTeX/pull/103).

**Comment by leftaroundabout** [comment]
This is just a leftover from https://github.com/Daniel-Diaz/HaTeX/pull/103, mostly I had already made the library compatible with the SemigroupMonoid proposal.

**Comment by peti** [comment]
I trust this is fixed in 3.19.0.0?

**Comment by Daniel-Diaz** [comment]
Yes.
